### ISSUE TITLE
AspectJ Compiler Exception (Jenkins Parallel Job) 

### ISSUE THREAD

**Issue by almayce** [freefair/gradle-plugins#216]
Hi!

Plugin: **io.freefair.gradle:aspectj-plugin:5.0.0-rc6**
I define it by testInpath method in my build.gradle:
```
apply plugin: 'java'
apply from: "dependencies.gradle"
apply from: "update-constant-task.gradle"
apply plugin: "io.freefair.aspectj.post-compile-weaving"

buildscript {
    repositories {
        jcenter()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72"
        classpath "io.freefair.gradle:aspectj-plugin:5.0.0-rc6"
    }
}

allprojects {
    apply plugin: 'java'
    apply plugin: 'kotlin'

    sourceCompatibility = 1.8

    repositories {
        jcenter()
        flatDir {
            dirs "$rootProject.projectDir"
        }
    }

    dependencies {
        testInpath(name :'libs/leadium-core') // MY ASPECT FILE IN THIS JAR 
    ...
    }
...
```

When I execute jenkins parallel job (5 threads, junit, selenium grid)
I've been faced this problem:

```
---- AspectJ Properties ---
AspectJ Compiler 1.9.5 built on Thursday Nov 28, 2019 at 11:28:53 PST
---- Dump Properties ---
Dump file: ajcore.20200422.205352.093.txt
Dump reason: java.io.FileNotFoundException
Dump on exception: true
Dump at exit condition: abort
---- Exception Information ---
java.io.FileNotFoundException: /var/lib/jenkins/workspace/BPM_UI_Test_Automation/Customer_On_Boarding_5_threads/source/apps/customeronboarding/build/classes/kotlin/test/customeronboarding/cases/primary/ui/create/retail/joint/BranchCheckerRejectCancel$begin$3$19.class (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.aspectj.weaver.bcel.BcelWeaver.addClassFile(BcelWeaver.java:464)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.initBcelWorld(AjBuildManager.java:908)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:253)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:189)
	at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:114)
	at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:60)
	at org.aspectj.tools.ajc.Main.run(Main.java:371)
	at org.aspectj.tools.ajc.Main.runMain(Main.java:248)
	at org.aspectj.tools.ajc.Main.main(Main.java:84)
---- System Properties ---
java.runtime.name=OpenJDK Runtime Environment
sun.boot.library.path=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre/lib/amd64
java.vm.version=25.212-b04
java.vm.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
path.separator=:
java.vm.name=OpenJDK 64-Bit Server VM
file.encoding.pkg=sun.io
sun.java.launcher=SUN_STANDARD
user.country=US
sun.os.patch.level=unknown
java.vm.specification.name=Java Virtual Machine Specification
user.dir=/var/lib/jenkins/workspace/BPM_UI_Test_Automation/Customer_On_Boarding_5_threads/source/apps/customeronboarding
java.runtime.version=1.8.0_212-b04
java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment
java.endorsed.dirs=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre/lib/endorsed
os.arch=amd64
java.io.tmpdir=/tmp
line.separator=

java.vm.specification.vendor=Oracle Corporation
user.variant=
os.name=Linux
sun.jnu.encoding=UTF-8
java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
java.specification.name=Java Platform API Specification
java.class.version=52.0
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
os.version=3.10.0-957.21.3.el7.x86_64
user.home=/var/lib/jenkins
user.timezone=UTC
java.awt.printerjob=sun.print.PSPrinterJob
file.encoding=UTF-8
java.specification.version=1.8
java.class.path=/var/lib/jenkins/.gradle/caches/modules-2/files-2.1/org.aspectj/aspectjtools/1.9.5/dfca1edabdca4f262d7f7c45cd8e11e6b88b9f6/aspectjtools-1.9.5.jar
user.name=jenkins
java.vm.specification.version=1.8
sun.java.command=org.aspectj.tools.ajc.Main -argfile /var/lib/jenkins/workspace/BPM_UI_Test_Automation/Customer_On_Boarding_5_threads/source/apps/customeronboarding/build/tmp/compileTestKotlin/ajc.options
java.home=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre
sun.arch.data.model=64
user.language=en
java.specification.vendor=Oracle Corporation
awt.toolkit=sun.awt.X11.XToolkit
java.vm.info=mixed mode
java.version=1.8.0_212
java.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre/lib/ext:/usr/java/packages/lib/ext
sun.boot.class.path=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre/lib/resources.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre/lib/rt.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre/lib/jsse.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre/lib/jce.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre/lib/charsets.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre/lib/jfr.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre/classes
java.vendor=Oracle Corporation
file.separator=/
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
sun.io.unicode.encoding=UnicodeLittle
sun.cpu.endian=little
sun.cpu.isalist=
---- Command Line ---
-argfile
/var/lib/jenkins/workspace/BPM_UI_Test_Automation/Customer_On_Boarding_5_threads/source/apps/customeronboarding/build/tmp/compileTestKotlin/ajc.options
---- Full Classpath ---
Empty
---- Compiler Messages ---
abort ABORT -- (FileNotFoundException) /var/lib/jenkins/workspace/BPM_UI_Test_Automation/Customer_On_Boarding_5_threads/source/apps/customeronboarding/build/classes/kotlin/test/customeronboarding/cases/primary/ui/create/retail/joint/BranchCheckerRejectCancel$begin$3$19.class (No such file or directory)
/var/lib/jenkins/workspace/BPM_UI_Test_Automation/Customer_On_Boarding_5_threads/source/apps/customeronboarding/build/classes/kotlin/test/customeronboarding/cases/primary/ui/create/retail/joint/BranchCheckerRejectCancel$begin$3$19.class (No such file or directory)
java.io.FileNotFoundException: /var/lib/jenkins/workspace/BPM_UI_Test_Automation/Customer_On_Boarding_5_threads/source/apps/customeronboarding/build/classes/kotlin/test/customeronboarding/cases/primary/ui/create/retail/joint/BranchCheckerRejectCancel$begin$3$19.class (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.aspectj.weaver.bcel.BcelWeaver.addClassFile(BcelWeaver.java:464)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.initBcelWorld(AjBuildManager.java:908)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:253)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:189)
	at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:114)
	at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:60)
	at org.aspectj.tools.ajc.Main.run(Main.java:371)
	at org.aspectj.tools.ajc.Main.runMain(Main.java:248)
	at org.aspectj.tools.ajc.Main.main(Main.java:84)
```
This issue is caused in 10-15% of all test cases of whole execution session.
Could you help me, please?

**Comment by larsgrefer** [comment]
What exactly is running in parallel?

**Comment by almayce** [comment]
Selenium tests within [Selenoid](https://github.com/aerokube/selenoid)

**Comment by Frisch12** [comment]
Is this still an issue?

**Comment by almayce** [comment]
so since I can't reproduce this issue, I think it can be closed
