### ISSUE TITLE
lombok overrides custom lombok.config files

### ISSUE THREAD

**Issue by jeusdi** [freefair/gradle-plugins#31]
I'm getting this error when `gradle compileJava`:

```
gradle compileJava                

> Task :frontoffice:compileJava
/home/jeusdi/projects/espaidoc/frontoffice/src/main/java/io/espaidoc/rest/service/cache/ReferenceCacheLoader.java:33: error: cannot find symbol
        LOG.info(
        ^
  symbol:   variable LOG
  location: class ReferenceCacheLoader
/home/jeusdi/projects/espaidoc/frontoffice/src/main/java/io/espaidoc/rest/service/UserService.java:11: error: cannot find symbol
        LOG.info("");
        ^
  symbol:   variable LOG
  location: class UserService
/home/jeusdi/projects/espaidoc/frontoffice/src/main/java/io/espaidoc/rest/resources/ReferenceResourceImpl.java:44: error: cannot find symbol
        LOG.info(RestConstants.Logs.UPLOAD_START, id);
        ^
  symbol:   variable LOG
  location: class ReferenceResourceImpl
3 errors

> Task :frontoffice:compileJava FAILED

FAILURE: Build failed with an exception.
```

As you can see, `LOG` field is not present.

Nevertheless, I've set a `lombok.config` unser `frontoffice/lombok.config` where:

    lombok.log.fieldName=LOG

Nevertheless, after task is executed, the content of this file is:

```
# This file is generated by the 'io.freefair.lombok' Gradle plugin
config.stopBubbling = true
lombok.addLombokGeneratedAnnotation = true
lombok.extern.findbugs.addSuppressFBWarnings = true
```

Any ideas?

**Comment by larsgrefer** [comment]
You can add this to your `build.gradle`:
```gradle
lombok.config['lombok.log.fieldName'] = 'LOG'
```

**Comment by jeusdi** [comment]
Ok, solved.

Could be this "action" disabled?
I mean, is there any way to keep custom `lombok.config` files instead of keep confiration on gradle script?

**Comment by larsgrefer** [comment]
Sure:

```gradle
generateLombokConfig.enabled = false
```

**Comment by chriswhite199** [comment]
On a similar note to this - in gradle multi-module project, if you have a lombok.config file at the top level, how can you stop this plugin from creating a lombok.config in each module folder?

Setting `generateLombokConfig.enabled = false` fails:

```
* Exception is:
org.gradle.api.tasks.TaskValidationException: A problem was found with the configuration of task ':module-1:compileJava'.
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.report(ValidatingTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.StartSnapshotTaskInputsBuildOperationTaskExecuter.execute(StartSnapshotTaskInputsBuildOperationTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:93)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:45)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:46)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.InvalidUserDataException: File '/Users/me/workspace/my-project/module-1/lombok.config' specified for property '$1' does not exist.
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.report(ValidatingTaskExecuter.java:64)
        ... 35 more

```

**Comment by larsgrefer** [comment]
@chriswhite199 Thanks for the stacktrace. This should definitely not happen (and be fixed in 34b3e6b)

The `javadoc.dependsOn delombok` and `javadoc.source = file("${buildDir}/delombok/main")` statements should be redundant. This is already done here: https://github.com/freefair/gradle-plugins/blob/34b3e6b34dd6a64da3874eb1a876c9c08333a0ff/lombok-plugin/src/main/java/io/freefair/gradle/plugins/lombok/LombokPlugin.java#L76

**Comment by chriswhite199** [comment]
@larsgrefer good to know. What's your release cycle like, ie when would that commit make it into a release?

**Comment by larsgrefer** [comment]
@chriswhite199 I've just released 3.5.2. It should be available from plugins.gradle.org within the next hour

**Comment by chriswhite199** [comment]
@larsgrefer  - just tried 3.5.2 with the following and still seeing the same issue / error:

```
    generateLombokConfig.enabled  = false
    // this line appears to still be required..
    // generateLombokConfig.outputFile.set(file("${rootDir}/lombok.config"))

    javadoc {
        failOnError = true
    }
```

**Comment by larsgrefer** [comment]
@chriswhite199 Please try again with `3.6.1`

**Comment by chriswhite199** [comment]
@larsgrefer that appears to have resolve it - many thanks!

**Comment by overfullstack** [comment]
I see `lombok.config` what's the right way to add @Generated annotation. I have lombok.config with `lombok.addLombokGeneratedAnnotation = true` but I don't get any annotations for generated code. Can someone please help. Cc: @larsgrefer 
Sample project: https://github.com/overfullstack/vader-root/blob/master/specs/build.gradle.kts

**Comment by larsgrefer** [comment]
The `lombok.config` files itselfs are'nt deprecated. They just won't be generated by the gradle plugin anymore.

You (as user of the gradle plugin) are expected to provide your own lombok.config files as described here: https://projectlombok.org/features/configuration

**Comment by overfullstack** [comment]
Thanks @larsgrefer , I have a multi-module gradle project ([Sample Project](https://github.com/overfullstack/vader-root/blob/master/specs/build.gradle.kts#L14))

I have the following lombok.config: 
```
config.stopBubbling = true
lombok.addLombokGeneratedAnnotation = true
lombok.extern.findbugs.addSuppressFBWarnings = true
```

Q1: This is a multi-module root-level, but only one module has lombok. Should I place it at module-root level?

Q2: Also, I have requirement where Kotlin picks up from delomboked code. When I see the generated code in `build/generated/sources/delombok/java/main/...` I don't see `@Generated` annotations. This is affecting my Jacoco test coverage. Please help. Thanks.

(I observed from a [sample single module project](https://github.com/overfullstack/untitled) that `@Genearated` annotations are being added to classes in `build/classes/java/main/...` but not to `build/generated/sources/delombok/java/main/...`, is this a bug or expected?)
I already raised an issue for this: #391
