### ISSUE TITLE
Gradle 8.0.1 delombok not working UnionFileFree

### ISSUE THREAD

**Issue by jlu1985** [freefair/gradle-plugins#732]
Hi Gradle 8.0.1 seems removed the internal class.
org.gradle.api.internal.file.UnionFileTree
 please look into a replacement Class. thanks

------------------------------------------------------------
Gradle 8.0.1
------------------------------------------------------------

Build time:   2023-02-17 20:09:48 UTC
Revision:     68959bf76cef4d28c678f2e2085ee84e8647b77a

Kotlin:       1.8.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          19.0.2 (Eclipse Adoptium 19.0.2+7)
OS:           Mac OS X 13.2.1 aarch64

* Exception is:
java.lang.NoSuchMethodError: 'void org.gradle.api.internal.file.UnionFileTree.<init>(java.lang.String, java.util.Collection)'
	at io.freefair.gradle.plugins.lombok.tasks.Delombok.getFilteredInput(Delombok.java:141)
	at io.freefair.gradle.plugins.lombok.tasks.Delombok_Decorated.getFilteredInput(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue$1.lambda$get$0(AbstractNestedRuntim

**Comment by larsgrefer** [comment]
Hi. Thanks for the detailed report.

which plugin version are you using?

**Comment by jlu1985** [comment]
Hi Im using it through gradle plugin block
plugins {
id("io.freefair.lombok") version "6.6.1"
}

thanks

**Comment by jlu1985** [comment]
6.6.3 seems working. i shall mark issue close. thanks
