### ISSUE TITLE
ClassNotFoundException: org.scilab.forge.jlatexmath.TeXFormula when using AsciiMath

### ISSUE THREAD

**Issue by jens-auer** [freefair/gradle-plugins#838]
Hi,

I am using Asciimath formulas (or Latex) in some of my diagrams. When I try to generate my document with my gradle build script I am getting above exception. Here is an example puml file with AsciiMath

```
@startuml StateMachine
skinparam linetype ortho

state A 
state B 
state C

[*] --> A: boot

A --> B:<math>"x"  = "0"</math>\n<math>"y" = "1"</math>
B --> C:<math>"x" = "y"</math>\n<math>wedge "z" in {"a", "b"}</math>\n<math>wedge "z" = "42"</math>

@enduml
```
and the exception when executing the build
```
formula=wedge "z" = "42"
Latex=\wedge\text{z}=\text{42}
java.lang.ClassNotFoundException: org.scilab.forge.jlatexmath.TeXFormula
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at net.sourceforge.plantuml.math.TeXIconBuilder.<init>(TeXIconBuilder.java:53)
        at net.sourceforge.plantuml.math.LatexBuilder.buildIcon(LatexBuilder.java:67)
        at net.sourceforge.plantuml.math.LatexBuilder.getImage(LatexBuilder.java:83)
        at net.sourceforge.plantuml.math.AsciiMath.getImage(AsciiMath.java:72)
        at net.sourceforge.plantuml.math.ScientificEquationSafe.getImage(ScientificEquationSafe.java:116)
        at net.sourceforge.plantuml.klimt.creole.atom.AtomMath.drawU(AtomMath.java:97)
        at net.sourceforge.plantuml.klimt.creole.SheetBlock1.drawU(SheetBlock1.java:199)
        at net.sourceforge.plantuml.klimt.creole.SheetBlock2.drawU(SheetBlock2.java:104)
        at net.sourceforge.plantuml.klimt.shape.TextBlockMarged.drawU(TextBlockMarged.java:85)
        at net.sourceforge.plantuml.svek.SvekLine.drawU(SvekLine.java:779)
        at net.sourceforge.plantuml.svek.SvekResult.drawU(SvekResult.java:106)
        at net.atmp.ImageBuilder.writeImageInternal(ImageBuilder.java:306)
        at net.atmp.ImageBuilder.write(ImageBuilder.java:256)
        at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFileInternal(CucaDiagramFileMakerSvek.java:130)
        at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFile(CucaDiagramFileMakerSvek.java:70)
        at net.atmp.CucaDiagram.exportDiagramInternal(CucaDiagram.java:435)
        at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:142)
        at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:198)
        at net.sourceforge.plantuml.PSystemUtils.exportDiagramsDefault(PSystemUtils.java:207)
        at net.sourceforge.plantuml.PSystemUtils.exportDiagrams(PSystemUtils.java:96)
        at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:190)
        at io.freefair.gradle.plugins.plantuml.PlantumlAction.execute(PlantumlAction.java:34)
```

I tried to solve this by adding implementation or compileClasspath dependencies in the gradle script, but it does not work probably because "[Since is bigger, you have to  separately, then unzip the 4 jar files (batik-all-1.7.jar, jlatexmath-minimal-1.0.3.jar, jlm_cyrillic.jar and jlm_greek.jar) in the same folder as PlantUML.jar.](https://plantuml.com/ascii-math)"

Is there a way to get AsciiMath rendering working?

**Comment by larsgrefer** [comment]
You could try to add `plantuml` dependencies:

```gradle
dependencies {
    plantuml "net.sourceforge.plantuml:plantuml:1.2023.10"
    plantuml "org.scilab.forge:jlatexmath:1.0.7"
}
```

**Comment by jens-auer** [comment]
Thanks, that solved it. I did not expect it because the plantuml doc explicitly says that the jars have to be in the same directory.
